### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by SasCezar** [gfxdisp/asap#4]
Hi,

I'm running some experiments to evaluate the time needed to create a list of pairs to compute. Using the python sample code given in the notebook, with a random matrix of size 100 it takes 2 sec on GPU and after 10 minutes on CPU, I stopped it.

Given that I would like to use it on matrices of size > 1000,  my questions are:
- Am I doing something wrong with it? 
- Is the example running in approximate mode? (the MatLab folder has an approx version, while the python no)
- Would be possible to parallelize the code? In the sense, is the algorithm parallelizable, without much effort, on CPU, with something like numba for example?  

Thanks for the info

**Comment by SasCezar** [comment]
Here is the code i use:

```python
import time
import asap_gpu
import asap_cpu
import numpy as np
GPU = False
for i in [70]:

    pwc_mat = np.random.randint(low=20, size=(i, i))
    t1 = time.perf_counter()
    if GPU:
        pairs = asap_gpu.ASAP(pwc_mat, mst_mode=True, cuda=True)
    else:
        N = np.shape(pwc_mat)[0]
        asap = asap_cpu.ASAP(N, selective_eig = True)
        pairs_to_compare = asap.run_asap(pwc_mat, mst_mode=True)
    t2 = time.perf_counter()
    print("Indeces from pwc_mat to compare:")
    print(pairs)

    print(f'Size {i} - Finished in {t2-t1} seconds')

```

**Comment by mikhailiuk** [comment]
Hi Cezar, 
Thanks for raising the issue! So with regards to your questions:
* Yes! You are doing everything right.
* I am planning to release an approximate version in the coming week. Although it does bring the computational speed up, it is achieved it the cost of accuracy. So if the computational performance is of concern I would strongly advice using the GPU version.
* Yes the code is very easy to parallelise on CPU. In fact, the heaviest computations happening in these two nested loops are completely independent  and can be very easily parallelised https://github.com/gfxdisp/asap/blob/ff71f49a1e508136a1a8fcc738fa238e2472f016/python/asap_cpu.py#L124 

I will have a chance to have a deeper look into parallelising on CPU next weekend. 

Otherwise please let me know if there is anything else I can help you with :) 

Best,

Aliaksei

**Comment by SasCezar** [comment]
Hi Aliaksei, thanks for the reply!

I will try to parallelize it and see if it runs faster; I'm currently checking all parallel libraries in Python, and will be a nice real case task. In case I get something before the weekend, I will make a PR.

I currently switched to the GPU code without CUDA, so I run Torch on the CPU and work super fast (almost as the laptop GPU). So I'm now looking for ways to reduce the memory footprint, as I'm having issues with memory usage. 100x100 matrix uses 12GB of RAM. 

A bit of an OT question, I read the paper, and from it, I understand that ASAP works faster and converges sooner to the optimum. However, this requires heavy computations and is not designed to be run on desktops (non-server machines). Therefore, as I'm not familiar with the domain, and I only (I know I'm asking for a lot) want to have a fast and easy way to reduce the workload on annotators (as they are volunteers), and also don't have fundings for a large server with GPU, can you suggest, if there is any quick and dirty solution for CPU with  > 1K of samples?  

I was thinking of having a sliding matrix (size ~300 or ~500) run over the > 1K matrix. However, the picked 'best' pairs will be local and might end in a worse place than a naive approach. 

Thanks!

**Comment by mikhailiuk** [comment]
Hi Cesar,

By all means you are very welcome to create a PR! We would be very grateful for your contribution!

As for a quicker less optimal solution, a sliding window might not be such a bad idea. You could also reduce the number of iterations in the posterior estimation of the trueskill algorithm, however that will also come at the cost of accuracy. Potentially you could also make selective EIG evaluations more aggressive. If the time waits I will be able to add these modifications over the weekend.

Thanks,

Aliaksei
